name: Build and Publish APK

on:
  push:
    branches:
      - main # 触发工作流的分支名称（例如推送主分支时触发）

jobs:
  build:
    runs-on: ubuntu-latest # 使用 Ubuntu 操作系统运行作业

    steps:
    - name: Checkout repository # 第一步：检出当前仓库代码
      uses: actions/checkout@v2 # 使用 GitHub 官方的检出操作

    - name: Set up JDK 11 # 第二步：设置 JDK 环境（Android 开发需要 JDK）
      uses: actions/setup-java@v1 # 使用官方 JDK 配置操作
      with:
        java-version: '11' # 指定 JDK 11（Android 项目通常需要此版本）

    - name: Clone the target repository # 第三步：克隆目标仓库（需要打包的项目）
      run: git clone https://github.com/mr-pangpang/q215613905_TVBox.git # 直接使用 git clone 命令

    - name: Set up environment # 第四步：配置构建环境
      working-directory: q215613905_TVBox # 切换到克隆的项目目录
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties # 写入 Android SDK 路径到 local.properties
        # 注意：需要确保 Android SDK 已安装且环境变量 ANDROID_HOME 已设置（后续步骤可能需要补充）

    - name: Build APK # 第五步：编译 APK
      working-directory: q215613905_TVBox/app # 进入项目中的 app 模块目录
      run: ./gradlew assembleRelease # 使用 Gradle 构建 release 版本的 APK
      # 注意：需要确保项目有 release 签名配置（见下方签名配置注意事项）

    - name: Upload APK as artifact # 第六步：将 APK 上传为构建产物（用于调试或后续步骤）
      uses: actions/upload-artifact@v2 # 使用 GitHub 官方上传操作
      with:
        name: app-release.apk # 构建产物的名称
        path: q215613905_TVBox/app/build/outputs/apk/release/app-release.apk # APK 文件路径

    - name: Create Release # 第七步：创建 GitHub Release
      id: create_release
      uses: actions/create-release@v1 # 使用官方创建 Release 操作
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的默认令牌
      with:
        tag_name: v1.0.${{ github.run_number }} # 版本标签（格式：v1.0.构建次数）
        release_name: Release v1.0.${{ github.run_number }} # 发布名称
        draft: false # 是否设为草稿（false 表示直接发布）
        prerelease: false # 是否设为预发布（false 表示正式发布）

    - name: Upload APK to Release # 第八步：将 APK 附加到 Release 中
      uses: actions/upload-release-asset@v1 # 使用官方上传 Release 资产操作
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }} # 使用 GitHub 提供的默认令牌
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # 从创建的 Release 获取上传地址
        asset_path: q215613905_TVBox/app/build/outputs/apk/release/app-release.apk # APK 文件路径
        asset_name: app-release.apk # 上传后的文件名
        asset_content_type: application/vnd.android.package-archive # 文件类型（APK 标准 MIME 类型）
