name: Build and Publish APK

on:
  push:
    branches:
      - main # 触发分支（如 main 或 master）
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 允许创建 Release

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新 Ubuntu 运行器

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4 # 使用最新版 checkout action

      # 2. 设置 JDK 17（Android 构建推荐 JDK 17 或更高版本）
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # 3. 安装 Android SDK 工具（使用最新版本）
      - name: Install Android SDK
        uses: android-actions/setup-android@v4
        with:
          android-tools-version: '8.0.0' # 最新 SDK 工具版本
          components: |
            platforms;android-34 # 根据项目需求修改 API 级别（最新稳定版）
            build-tools;34.0.0 # 对应的构建工具版本
            platform-tools
            ndk;26.1.10909125 # 如果需要原生支持，使用最新 NDK 版本

      # 4. 克隆目标项目仓库（需替换为你的 TVBox 项目地址）
      - name: Clone Target Repository
        run: git clone https://github.com/mr-pangpang/q215613905_TVBox.git

      # 5. 配置签名密钥（通过 GitHub Secrets 存储敏感信息）
      - name: Configure Keystore
        run: |
          echo "storeFile=${{ secrets.KEYSTORE_FILE }}" > keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      # 6. 将签名文件复制到项目目录
      - name: Copy Keystore to Project
        run: |
          mkdir -p q215613905_TVBox/app
          cp keystore.properties q215613905_TVBox/app/

      # 7. 配置项目环境（设置 Android SDK 路径）
      - name: Setup Project Environment
        working-directory: q215613905_TVBox
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      # 8. 构建 Release APK
      - name: Build Release APK
        working-directory: q215613905_TVBox/app
        run: ./gradlew assembleRelease --stacktrace # 添加调试信息

      # 9. 上传 APK 为构建产物（用于调试）
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      # 10. 创建 GitHub Release（使用最新 release action）
      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.${{ github.run_number }}" # 版本号格式
          release_name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false

      # 11. 将 APK 附加到 Release（使用最新上传 action）
      - name: Upload APK to Release
        uses: ncipollo/release-action@v2.1.1
        with:
          artifacts: "q215613905_TVBox/app/build/outputs/apk/release/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
